apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-07T20:44:52Z
  labels:
    app: hello-world
  name: hello-loadbalance
  namespace: default
  resourceVersion: "1079"
  selfLink: /api/v1/namespaces/default/services/hello-loadbalance
  uid: 7e3639d8-5237-11e8-816b-42010a8a0183
spec:
  clusterIP: 10.63.246.249
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30995
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.233.173.198

